### ISSUE TITLE
Repository

### ISSUE THREAD

**Issue by nartesh** [nartesh/CheckMK_Plugin_zum_Monitoring_Festplatten#1]
Hallo @TobiasSMI

Ich habe diese Repository für mein checkmk Projekt erstellt. Allerdings möchte ich es schließlich zu verbessern und möchte ich wissen, ob es ok ist, welche Dateien ich hier hochgeladen soll und auf diese Weise kannst du Quellcode haben.

**Comment by TobiasSMI** [comment]
Hi @nartesh ... sorry für die späte Rückmeldung... ich hatte mir das Projekt seinerzeit als .zip runtergeladen. Daher wäre das für mich überhaupt kein Problem.
Hoffe dir geht es soweit gut.
LG Tobias
